---
language: go
go:
- 1.12.x
- tip
- 1.11.x
- 1.10.x
- 1.9.x
- 1.8.x
sudo: false

go_import_path: github.com/blueboardio/cldr

before_install:
- go get -t -v ./...

script:
- ./test.sh

after_success:
- bash <(curl -s https://codecov.io/bash)
